version: "2.4"
services:
  consul:
    image: consul:latest
    platform: linux
    hostname: consul
    environment:
      - 'CONSUL_LOCAL_CONFIG={"disable_update_check": true}'
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
    networks:
      - bridge_network
    command: "agent -server -bind={{GetPrivateIP}} -client=0.0.0.0 -dev -ui -enable-script-checks -log-level=warn"
    mem_limit: 512000000

  fabio:
    image: magiconair/fabio:latest
    platform: linux
    hostname: fabio
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    depends_on:
      consul:
        condition: service_started
    ports:
      - "9998:9998"
      - "9999:9999"
    networks:
      - bridge_network
    mem_limit: 512000000

  mountebank:
    image: andyrbell/mountebank:latest
    platform: linux
    hostname: mountebank
    links:
      - consul
    ports:
      - "2525:2525"
      - "3535:3535"
      - "4545:4545"
    networks:
      - bridge_network
    volumes:
      - type: bind
        source: ./mountebank
        target: /app/mountebank/config
    command: "mb --configfile /app/mountebank/config/config.ejs --loglevel info"

  newman:
    image: postman/newman:latest
    platform: linux
    hostname: newman
    links:
      - consul
      - fabio
    depends_on:
      consul:
        condition: service_started
      fabio:
        condition: service_started
    volumes:
      - type: bind
        source: ./postman
        target: /etc/postman
    networks:
      - bridge_network
    command: "run /etc/postman/RegisterMockServicesInConsul.postman_collection.json --environment=/etc/postman/Service-Registration-Docker-Env.postman_environment.json"

networks:
  bridge_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
